# fly.toml app configuration file generated for pharm-barcode on 2025-07-23T10:29:40-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pharm-barcode'
primary_region = 'iad'

[build]

[env]
  NODE_ENV = 'production'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
