# fly.toml app configuration file generated for barcode-generator-empty-haze-6135 on 2025-07-22T14:57:07-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'barcode-generator-empty-haze-6135'
primary_region = 'iad'

[build]

[env]
  NODE_ENV = 'production'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
